language: node_js

node_js: 6

cache:
  directories:
    - ../skygear-doc/node_modules

before_install:
  # Install AWS CLI
  - export PATH=$PATH:$HOME/.local/bin
  - pip install --user awscli
  # Checkout SkygearIO/skygear-doc while preserving node_modules cache
  - mkdir -p ../skygear-doc
  - cd ../skygear-doc
  - git clone -b ${TRAVIS_BRANCH:-master} --depth 1 --no-checkout https://github.com/SkygearIO/skygear-doc.git tmp
  - mv tmp/.git .
  - rm -rf tmp
  - git reset --hard HEAD
  # Create soft link on content folder
  - rm -rf content && ln -s $TRAVIS_BUILD_DIR content

script:
  - npm run spell-check

before_deploy:
  - npm run build release
  - ./scripts/before-deploy.sh

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $STAGING_BUCKET
    skip_cleanup: true
    acl: public_read
    local_dir: build
    on:
      repo: SkygearIO/guides
      branch: $STAGING_BRANCH
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $PRODUCTION_BUCKET
    skip_cleanup: true
    acl: public_read
    local_dir: build
    on:
      repo: SkygearIO/guides
      branch: $PRODUCTION_BRANCH

after_deploy:
  - ./scripts/after-deploy.sh

env:
  global:
    - PRODUCTION_BRANCH="production"
    - STAGING_BRANCH="staging"
    - PRODUCTION_BUCKET="docs.skygear.io"
    - STAGING_BUCKET="docs-staging.skygear.io"
    - DISTRIBUTION_ID="E31J8XF8IPV2V"

notifications:
  slack:
    rooms:
      secure: Z78dJi2Ew2HjXUnz6FMQcbZyktQRrFPN9NhUEnhhrT8LXYTOEglsK++0X1M+PWcFAmEEoe0YQjGauTkj/c3GuU5gM8hw5p49m6fojzq5d6eCkDbgtTp0/PPCm8As8laLoaqduHdiv9HqCuqVgLF33c5Jiosqcb5waxwUSGydIsqcNVWycspJAvCa/86WG8Q4RaNL9e3HhGBOjLR/UztA9CFur1XzzUWgVbpMcVvUDRjbpom3+DNnIiIoDGr05ZuvtNh38DvIzMQPnEGYiX67jbSZLnKq3i8GvoJk7GthFihRwRRdUpHaLq9J1W3BOsHgbPk2WkHO1W6NExuniyR2unp7p/aRUnOQ3Rz9BpkFgByY4dqcLQSRnFgaqWlW5a558h0dbwz/i5CC72O1dR8SU5tRKeIOphUsVueSioKL9fD1n8+ZzRP3zuTX5eolYwv8B9HtZUxRtiglICprABDolyRPkHLZXohr2gn4HXW6oWxLUyFuf2TlErSoYMixHL/8kG+uP8SwNRw4o/RNteqVepBkTWC9Wj314TMMl4IviB0ompqAL7SyXo1T3oqXZDcFvLQuTaEsYcbW5uy5FD74NakCtaJrN+RusXhYVAAUZ3qMRkQtuzk7vpN3LBLcRAHgmnK+QgAGYeRGlAqnldFWdcVz2ndinX0C7OQcW6jJFGw=
